name: codeable_cli
description: >-
  A CLI tool that scaffolds production-ready Flutter projects with Clean
  Architecture, BLoC/Cubit, Dio, Hive, GoRouter, multi-flavor builds,
  and Firebase integration.
version: 1.0.6
repository: https://github.com/Arhamss/codeable-flutter-cli
issue_tracker: https://github.com/Arhamss/codeable-flutter-cli/issues

environment:
  sdk: ^3.11.0

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.11.1
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.29.0
  very_good_analysis: ^10.2.0

executables:
  codeable_cli:
