name: my_dart_cli
description: CLI for bootstrapping Codeable Flutter architecture projects
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  args: ^2.7.0
  cli_completion: ^0.5.1
  mason_logger: ^0.3.3
  pub_updater: ^0.5.0

dev_dependencies:
  build_runner: ^2.11.1
  build_verify: ^3.1.1
  build_version: ^2.1.3
  mocktail: ^1.0.4
  test: ^1.29.0
  very_good_analysis: ^10.2.0

executables:
  codeable_cli:
